/* @flow */
// AUTHENTICATE EVENTS
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RESTORE_SESSION = "RESTORE_SESSION";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// TRACKING EVENTS
export const SET_CURRENT_SCREEN = "SET_CURRENT_SCREEN";
export const SET_CURRENT_TAB = "SET_CURRENT_TAB";
//COMMON EVENTS
export const COMMON_INIT_STATE = "COMMON_INIT_STATE";



